### ISSUE TITLE
manifest-tool 1.0.0 fails to run on s390x (sometimes?)

### ISSUE THREAD

**Issue by tianon** [estesp/manifest-tool#86]
Here's the backtrace:

```console
$ manifest-tool push from-spec ...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

goroutine 97 [running]:
runtime: unexpected return pc for runtime.sigpanic called from 0x0
stack: frame={sp:0xc0001271b0, fp:0xc0001271d8} stack=[0xc000124000,0xc000128000)
000000c0001270b0:  000000c000240930  000000000070eaa0 
000000c0001270c0:  0000000000adc790  010000c000127110 
000000c0001270d0:  0000000000000000  00000000000457d0 <runtime.fatalpanic+80> 
000000c0001270e0:  0000000000045196 <runtime.gopanic+806>  000000c0001270f8 
000000c0001270f0:  0000000000044b60 <runtime.preprintpanics+64>  0000000000073c00 <runtime.fatalpanic.func1+0> 
000000c000127100:  000000c000127188  000000c0002b0780 
000000c000127110:  0000000000045196 <runtime.gopanic+806>  000000c000127128 
000000c000127120:  000000c0001270f0  000000000005d94a <runtime.sigpanic+1098> 
000000c000127130:  000000c000127188  000000000066c0d0 
000000c000127140:  000000c000127f50  0000000800000008 
000000c000127150:  000000000027d0ae <crypto/tls.(*Conn).Handshake+142>  0000000000000000 
000000c000127160:  000000c000127ec0  000000c0002b0780 
000000c000127170:  0000000000000000  000000c000127f20 
000000c000127180:  000000c0002b07a8  0000000000000000 
000000c000127190:  000000000056aaa0  000000c000240930 
000000c0001271a0:  0000000000000000  0000000000000000 
000000c0001271b0: <0000000000000000  000000000059ea20 
000000c0001271c0:  0000000000adc790  0000000000000000 
000000c0001271d0:  0000000000000000 >0000000000000000 
000000c0001271e0:  0000000000000000  0000000000000000 
000000c0001271f0:  0000000000000000  0000000000000000 
000000c000127200:  0000000000000000  0000000000000000 
000000c000127210:  0000000000000000  0100000000000000 
000000c000127220:  0000000000000000  0000000000000000 
000000c000127230:  0000000000000000  0000000000000000 
000000c000127240:  0000000000000000  0000000000000000 
000000c000127250:  0000000000000000  0000000000000000 
000000c000127260:  0000000000000000  0000000000000000 
000000c000127270:  0000000000000000  0000000000000000 
000000c000127280:  0000000000000000  0000000000000000 
000000c000127290:  0000000000000000  0000000000000000 
000000c0001272a0:  0000000000000000  0000000000000000 
000000c0001272b0:  0000000000000000  0000000000000000 
000000c0001272c0:  0000000000000000  0000000000000000 
000000c0001272d0:  0000000000000000 
panic(0x59ea20, 0xadc790)
	/usr/local/go/src/runtime/panic.go:722 +0x326
runtime: unexpected return pc for runtime.sigpanic called from 0x0
stack: frame={sp:0xc0001271b0, fp:0xc0001271d8} stack=[0xc000124000,0xc000128000)
000000c0001270b0:  000000c000240930  000000000070eaa0 
000000c0001270c0:  0000000000adc790  010000c000127110 
000000c0001270d0:  0000000000000000  00000000000457d0 <runtime.fatalpanic+80> 
000000c0001270e0:  0000000000045196 <runtime.gopanic+806>  000000c0001270f8 
000000c0001270f0:  0000000000044b60 <runtime.preprintpanics+64>  0000000000073c00 <runtime.fatalpanic.func1+0> 
000000c000127100:  000000c000127188  000000c0002b0780 
000000c000127110:  0000000000045196 <runtime.gopanic+806>  000000c000127128 
000000c000127120:  000000c0001270f0  000000000005d94a <runtime.sigpanic+1098> 
000000c000127130:  000000c000127188  000000000066c0d0 
000000c000127140:  000000c000127f50  0000000800000008 
000000c000127150:  000000000027d0ae <crypto/tls.(*Conn).Handshake+142>  0000000000000000 
000000c000127160:  000000c000127ec0  000000c0002b0780 
000000c000127170:  0000000000000000  000000c000127f20 
000000c000127180:  000000c0002b07a8  0000000000000000 
000000c000127190:  000000000056aaa0  000000c000240930 
000000c0001271a0:  0000000000000000  0000000000000000 
000000c0001271b0: <0000000000000000  000000000059ea20 
000000c0001271c0:  0000000000adc790  0000000000000000 
000000c0001271d0:  0000000000000000 >0000000000000000 
000000c0001271e0:  0000000000000000  0000000000000000 
000000c0001271f0:  0000000000000000  0000000000000000 
000000c000127200:  0000000000000000  0000000000000000 
000000c000127210:  0000000000000000  0100000000000000 
000000c000127220:  0000000000000000  0000000000000000 
000000c000127230:  0000000000000000  0000000000000000 
000000c000127240:  0000000000000000  0000000000000000 
000000c000127250:  0000000000000000  0000000000000000 
000000c000127260:  0000000000000000  0000000000000000 
000000c000127270:  0000000000000000  0000000000000000 
000000c000127280:  0000000000000000  0000000000000000 
000000c000127290:  0000000000000000  0000000000000000 
000000c0001272a0:  0000000000000000  0000000000000000 
000000c0001272b0:  0000000000000000  0000000000000000 
000000c0001272c0:  0000000000000000  0000000000000000 
000000c0001272d0:  0000000000000000 
runtime.panicmem(...)
	/usr/local/go/src/runtime/panic.go:199
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:394 +0x44a
created by net/http.(*persistConn).addTLS
	/usr/local/go/src/net/http/transport.go:1397 +0x1b4
```

I'm not 100% sure the exact cause, but 1.0.0 was built against Go 1.13(.0), and testing a build against Go 1.13.8 was successful.  Looking through https://github.com/golang/go/compare/go1.13...go1.13.8, my best guess is https://github.com/golang/go/commit/4cb22ee8120ddd9cd8a9ef88ae2a142c5d2f8432 (crypto related s390x fix that talks about a panic), but I haven't done a full bisect of Go to confirm the exact commit. :innocent:

Any chance we could get a 1.0.1 or something that's built against a newer Go 1.13 release? :smile:

(See https://github.com/docker-library/golang/issues/321 for a downstream effect of this.  Our alternative is going to be to build our own `manifest-tool` binaries, so we figured it was worth asking you to do that instead! :1st_place_medal: :heart:)

**Comment by estesp** [comment]
Please test the [v1.0.1 release](https://github.com/estesp/manifest-tool/releases/tag/v1.0.1) and let me know if this solves the issue.  Thanks!

**Comment by tianon** [comment]
Sorry for the delay -- had to get it deployed, then had to get a case where we actually invoke `manifest-tool` (on `s390x` no less) to give it a proper test; https://doi-janky.infosiftr.net/job/multiarch/job/s390x/job/python/2160/execution/node/760/log/ confirms this was successful! (`Putting s390x/python:3.7.7` followed by no hairy backtrace)

Thanks so much, @estesp! :heart: :metal:
